#!/usr/bin/env bash
# Launch the freshly built KiCad, staging the packaged data it needs at runtime.
#
# KICAD_RUN_FROM_BUILD_DIR makes GetStockDataPath() prefer the build root over
# KICAD_STOCK_DATA_HOME, so translations, demos and stock scripting plugins have to
# exist under build/ or they are simply missing.  Staging happens here rather than in
# the flake's shellHook because a shell hook runs before every build, and cannot know
# whether CMake has written the files it owns yet -- schemas/api.v1.schema.json is
# generated by the build *and* present in the packaged tree, so staging early lands a
# read-only store symlink exactly where CMake is about to write.
#
# Usage: ./run-kicad.sh [kicad args...]     e.g. ./run-kicad.sh kicad/demos/.../x.kicad_pro
set -euo pipefail

cd "$(dirname "$0")"

if [ ! -x build/kicad/kicad ]; then
    echo "build/kicad/kicad not found -- build first:" >&2
    echo "  nix develop -c cmake --build build -j\$(nproc)" >&2
    exit 1
fi

: "${KICAD_PACKAGED_DATA:?not set -- run inside 'nix develop'}"

# Symlink farm: real directories, symlinked leaves, never clobbering build output.
# `cp -r` would otherwise copy the store's read-only directory modes, leaving a tree
# that cannot be cleaned up or written to, so make what we create writable again.
cp -rsn "$KICAD_PACKAGED_DATA"/. build/ 2>/dev/null || true
chmod -R u+w build 2>/dev/null || true

exec ./build/kicad/kicad "$@"
